const data = [
  {
    id: 1,
    courseName: "Android",
    mentor: "Allayarov Otabek",
    technology: "Kotlin",
    price: "250 000 som/oy",
    duration: "6oy-9oy",
  },
  {
    id: 2,
    courseName: "Kompyuter Savodxonligi",
    mentor: "Abdullayev Sultonbek",
    technology: "Word, Excel,PowerPoint",
    price: "200 000 som/oy",
    duration: "1oy",
  },
  {
    id: 3,
    courseName: "Front End",
    mentor: "Tursinbayev Shukurulla",
    technology: "HTML,CSS,JavaScript,ReactJS",
    price: "250 000 som/oy",
    duration: "6oy-9oy",
  },
  {
    id: 4,
    courseName: "IT Matematika",
    mentor: "Samandar",
    technology: "Algebra, Geometriya",
    price: "220 000 som/oy",
    duration: "6oy-9oy",
  },
  {
    id: 5,
    courseName: "IT English",
    mentor: "Undefined",
    technology: "Ingliz tili",
    price: "220 000 som/oy",
    duration: "6oy-9oy",
  },
  {
    id: 6,
    courseName: "Python",
    mentor: "Qayrat",
    technology: "Python",
    price: "250 000 som/oy",
    duration: "3oy-6oy",
  },
  {
    id: 7,
    courseName: "Grafik Dizayn",
    mentor: "Batir",
    technology: "Photoshop, CorelDraw",
    price: "220 000 som/oy",
    duration: "3oy-6oy",
  },
];

export default data;
